name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1 - Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2 - Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      #Step 3 - Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4 - Generate Prisma client
      - name: Generate Prisma client
        run: npx prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      #Step 5 - Lint check
      - name: Lint
        run: npm run lint

      #Step 6 - Build
      - name: Build
        run: npm run build

      #Step 7 - Run test
      - name: Run test
        run: npm test -- --passWithNoTests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      # Step 8 - Test coverage
      - name: Test coverage
        run: npm run test:cov -- --passWithNoTests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      # Step 9 - Build Docker image
      - name: Build Docker image
        run: docker build -t nestjs-demo .
